title: "Blog Title"
author: "Blog Author"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
lang: "en"
excerpt_separator: "\n\n\n"

# Page Settings
date_format: "%B %d, %Y"
#permalink: /:title/
paginate: 4

# Google Analytics
#google_analytics: G-F80DVB221P

# Google Adsense
#google_adsense: ca-pub-1234567890123456

# Layout

show_excerpts: true       # show article excerpts on the home page
show_frame: false         # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: true             # use a dark header

# theme: jekyll-theme-modernist

# # Theme Settings
# hide_title: false         # remove site heading in the header
# hide_footer: false        # hide the "previous" and "next" links at the end of each post
# dark_theme: true          # use the dark mode as default
# dark_header: true         # keep the header dark
# dark_footer: true         # keep the footer dark

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "archive.html"}
  - {file: "README.md"}
  # - {file: "index.html", icon: blog}
  # - {file: "archive.html", icon: list}
  # - {file: "README.md", icon: user}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  # - {title: Gitlab, icon: gitlab, url: "https://gitlab.com/mcgarrah"}
  # - {title: StackOverflow, icon: stack-overflow, url: "https://stackoverflow.com/users/2452678/michael-mcgarrah"}
  # - {title: Discord, icon: discord, url: "https://discord.com/users/914581392740995073"}
  # - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/michaelmcgarrah/"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

# Make sure Gemfile has these in the plugin section
plugins:
 - jekyll-feed             # used for RSS XML feed
 - jekyll-sitemap          # plugin to silently generate a sitemaps.org compliant sitemap
 - jekyll-paginate         # adding back from earlier implementation in upstream fork
