title: "Technical Blog"
author: "Michael McGarrah"
description: "Michael McGarrah's Technical Blog"
lang: "en"

# Page Settings
permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
paginate: 4

# Layout
show_excerpts: true       # show article excerpts on the home page
show_frame: false         # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# theme: jekyll-theme-modernist

# # Theme Settings
# hide_title: false         # remove site heading in the header
# hide_footer: false        # hide the "previous" and "next" links at the end of each post
# dark_theme: true          # use the dark mode as default
# dark_header: true         # keep the header dark
# dark_footer: true         # keep the footer dark

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: blog}
  - {file: "archive.html", icon: list}
  - {file: "README.md", icon: user}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mcgarrah@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/mcgarrah"}
  - {title: Resume, icon: file, sidebaricon: file, url: "/resume/"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/James-Mcgarrah"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0001-8935-1293"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=Lt7T2SwAAAAJ"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/        - needs money or ad-verts
#  isso_domain: ""         # see https://posativ.org/isso/  - python hosted service with sqlite (money for hosting server)

plugins:
 - jekyll-feed             # used for RSS XML feed
 # - jekyll-paginate         # adding back from earlier implementation in upstream fork
