title: "McGarrah Technical Blog"
author: "Michael McGarrah"
description: "Technical blog covering homelab infrastructure, Proxmox/Ceph, Dell Wyse 3040, Jekyll development, and networking. Deep dives into virtualization, storage clustering, and system administration."
lang: "en"
url: "https://www.mcgarrah.org"
baseurl: ""

# Canonical URL configuration for SEO
canonical_url: "https://www.mcgarrah.org"

# SEO Configuration
seo:
  type: Person
  name: "Michael McGarrah"
  links:
    - "https://www.linkedin.com/in/michaelmcgarrah/"
    - "https://github.com/mcgarrah"
    - "https://gitlab.com/mcgarrah"
    - "https://stackoverflow.com/users/2452678/michael-mcgarrah"
    - "https://orcid.org/0000-0001-8935-1293"
    - "https://scholar.google.com/citations?user=Lt7T2SwAAAAJ"

# Social Media
# twitter:
#   username: mcgarrah
#   card: summary_large_image

# Logo for structured data
logo: "/assets/images/logo.png"

# Google Analytics
google_analytics: G-F90DVB199P

# Google Adsense
google_adsense: ca-pub-2421538118074948

# Google Custom Search
# Replace with your full CSE ID from Google Custom Search console
# Format: "012345678901234567890:abcdefghijk" or just "abcdefghijk"
google_cse_id: "50dc9b6524efa45a0" 
google_cse_label: "McGarrah Blog Search"

# Page Settings
permalink: /:title/
#excerpt_separator: "\n\n\n"
excerpt_separator: <!-- excerpt-end -->
date_format: "%B %d, %Y"
paginate: 4

# Future posts disabled for scheduled releases via GHA scheduled job
#future: true
future: false

# Layout
show_excerpts: true       # show article excerpts on the home page
show_frame: false         # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# theme: jekyll-theme-modernist

# # Theme Settings
# hide_title: false         # remove site heading in the header
# hide_footer: false        # hide the "previous" and "next" links at the end of each post
# dark_theme: true          # use the dark mode as default
# dark_header: true         # keep the header dark
# dark_footer: true         # keep the footer dark

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: blog}
  - {file: "archive.html", icon: list}
  - {file: "tags.html", title: Tags, icon: tags}
  - {file: "categories.html", title: Categories, icon: th-list}
  - {file: "search.html", title: Search, icon: search}
  - {file: "README.md", icon: user}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mcgarrah@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/mcgarrah"}
  - {title: Gitlab, icon: gitlab, url: "https://gitlab.com/mcgarrah"}
  - {title: StackOverflow, icon: stack-overflow, url: "https://stackoverflow.com/users/2452678/michael-mcgarrah"}
  - {title: Discord, icon: discord, url: "https://discord.com/users/914581392740995073"}
  - {title: Resume, icon: file, sidebaricon: file, url: "/resume/"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/michaelmcgarrah/"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/James-Mcgarrah"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0001-8935-1293"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=Lt7T2SwAAAAJ"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/        - needs money or ad-verts
#  isso_domain: ""         # see https://posativ.org/isso/  - python hosted service with sqlite (money for hosting server)

plugins:
 - jekyll-feed             # used for RSS XML feed
 - jekyll-sitemap          # plugin to silently generate a sitemaps.org compliant sitemap
 - jekyll-paginate         # adding back from earlier implementation in upstream fork
 - jekyll-seo-tag          # comprehensive SEO meta tags and structured data
giscus:
  repo: mcgarrah/mcgarrah.github.io
  repo_id: R_kgDOKBKIdw
  category: Announcements
  category_id: DIC_kwDOKBKId84Cq3DK
  mapping: pathname # Options: pathname, url, title, og:title, specific, number
  strict: 0 # Boolean: 0 or 1
  reactions_enabled: 1 # Boolean: 0 or 1
  emit_metadata: 0 # Boolean: 0 or 1
  input_position: bottom # Options: top, bottom
  theme: preferred_color_scheme # Options: light, dark, dark_dimmed, dark_high_contrast, preferred_color_scheme, transparent_dark,noborder_light, noborder_dark, cobal, or a custom CSS URL
  lang: en
  loading: lazy # Options: eager, lazy


