      - name: Check links with Lychee
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          args: --config .lychee.toml --root-dir . --no-progress '_site/**/*.html'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
